// Command schemadoc generates docs/config.md from the HCL struct tags and the
// prose in nns/schema.go. Run via `go generate ./nns`. It fails if any
// documented field lacks a description or a described field no longer exists,
// so the docs stay in lockstep with the structs.
package main

import (
	"flag"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"

	"github.com/swiss-subnet/alpage/nns"
)

type field struct {
	Name     string
	Kind     string // "attr", "block", or "label"
	Optional bool
	Doc      string
}

func main() {
	out := flag.String("out", "docs/config.md", "output markdown path")
	flag.Parse()

	md, err := render()
	if err != nil {
		fmt.Fprintln(os.Stderr, "schemadoc:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, []byte(md), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "schemadoc:", err)
		os.Exit(1)
	}
	fmt.Println("wrote", *out)
}

func render() (string, error) {
	used := map[string]bool{}
	var b strings.Builder
	b.WriteString("<!-- Generated by cmd/schemadoc from nns/schema.go. Do not edit by hand; run `go generate ./nns`. -->\n\n")
	b.WriteString("# Config schema\n\n")
	b.WriteString("Alpage config is HCL. The blocks below are the complete schema; it is generated from the `hcl:\"...\"` struct tags in `nns/`, so it always matches what the tool parses.\n\n")

	byFile := map[string][]nns.SchemaBlock{}
	var order []string
	for _, blk := range nns.SchemaBlocks {
		if _, ok := byFile[blk.File]; !ok {
			order = append(order, blk.File)
		}
		byFile[blk.File] = append(byFile[blk.File], blk)
	}

	for _, f := range order {
		fmt.Fprintf(&b, "## `%s`\n\n", f)
		for _, blk := range byFile[f] {
			if err := renderBlock(&b, blk, used); err != nil {
				return "", err
			}
		}
	}

	var unused []string
	for k := range nns.SchemaFieldDocs {
		if !used[k] {
			unused = append(unused, k)
		}
	}
	if len(unused) > 0 {
		sort.Strings(unused)
		return "", fmt.Errorf("SchemaFieldDocs has entries for fields that no longer exist: %s", strings.Join(unused, ", "))
	}
	return b.String(), nil
}

func renderBlock(b *strings.Builder, blk nns.SchemaBlock, used map[string]bool) error {
	header := blk.Name
	for _, l := range blk.Labels {
		header += fmt.Sprintf(" \"<%s>\"", l)
	}
	fmt.Fprintf(b, "### `%s { }`\n\n%s\n\n", header, blk.Doc)

	fields, err := fieldsOf(blk, used)
	if err != nil {
		return err
	}
	if len(fields) == 0 {
		return nil
	}
	b.WriteString("| Field | Kind | Required | Description |\n")
	b.WriteString("|-------|------|----------|-------------|\n")
	for _, f := range fields {
		req := "yes"
		if f.Optional || f.Kind == "block" {
			req = "no"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", f.Name, f.Kind, req, f.Doc)
	}
	b.WriteString("\n")
	return nil
}

func fieldsOf(blk nns.SchemaBlock, used map[string]bool) ([]field, error) {
	t := reflect.TypeOf(blk.Type)
	structName := t.Name()
	var out []field
	for _, sf := range hclFields(t) {
		tag := sf.Tag.Get("hcl")
		if tag == "" || tag == ",remain" {
			continue
		}
		name, opts, _ := strings.Cut(tag, ",")
		f := field{Name: name}
		switch {
		case strings.Contains(","+opts+",", ",label,") || opts == "label":
			f.Kind = "label"
		case strings.Contains(","+opts+",", ",block,") || opts == "block":
			f.Kind = "block"
		default:
			f.Kind = "attr"
		}
		f.Optional = strings.Contains(","+opts+",", ",optional,") || opts == "optional"

		if f.Kind == "label" {
			continue // labels are shown in the block header
		}
		key := structName + "." + name
		doc, ok := nns.SchemaFieldDocs[key]
		if !ok {
			return nil, fmt.Errorf("missing SchemaFieldDocs[%q] for %s block %q", key, blk.Name, name)
		}
		used[key] = true
		f.Doc = doc
		out = append(out, f)
	}
	return out, nil
}

// hclFields returns the struct's fields in declaration order, recursing into
// embedded (anonymous) structs so a base like `named` flattens into the
// enclosing block, matching how gohcl decodes them.
func hclFields(t reflect.Type) []reflect.StructField {
	var out []reflect.StructField
	for i := 0; i < t.NumField(); i++ {
		sf := t.Field(i)
		if sf.Anonymous && sf.Type.Kind() == reflect.Struct {
			out = append(out, hclFields(sf.Type)...)
			continue
		}
		out = append(out, sf)
	}
	return out
}
