// Command schemadoc generates docs/config.md from the HCL struct tags and the
// prose in nns/schema.go. Run via `go generate ./nns`. It fails if any
// documented field lacks a description or a described field no longer exists,
// so the docs stay in lockstep with the structs.
package main

import (
	"flag"
	"fmt"
	"os"
	"reflect"
	"regexp"
	"sort"
	"strings"

	"github.com/swiss-subnet/alpage/nns"
)

type field struct {
	Name     string
	Kind     string // "attr", "block", or "label"
	Optional bool
	Doc      string
	Since    string
}

func main() {
	out := flag.String("out", "docs/config.md", "output markdown path")
	flag.Parse()

	md, err := render()
	if err != nil {
		fmt.Fprintln(os.Stderr, "schemadoc:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, []byte(md), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "schemadoc:", err)
		os.Exit(1)
	}
	fmt.Println("wrote", *out)
}

func render() (string, error) {
	used := map[string]bool{}
	var b strings.Builder
	b.WriteString("<!-- Generated by cmd/schemadoc from nns/schema.go. Do not edit by hand; run `go generate ./nns`. -->\n\n")
	b.WriteString("# Config Schema\n\n")
	b.WriteString("Alpage config is HCL. The blocks below are the complete schema; it is generated from the `hcl:\"...\"` struct tags in `nns/`, so it always matches what the tool parses.\n\n")
	intro := "This page documents the schema as of the latest release."
	if nns.SchemaUnreleased != "" {
		intro = "This page documents the current development schema, ahead of the latest release."
	}
	b.WriteString(intro + " The Since column gives the release each block and field first appeared in, so a field newer than your binary is visible as such; see [Schema History](#schema-history) for the schema as of each release.\n\n")

	byFile := map[string][]nns.SchemaBlock{}
	var order []string
	for _, blk := range nns.SchemaBlocks {
		if _, ok := byFile[blk.File]; !ok {
			order = append(order, blk.File)
		}
		byFile[blk.File] = append(byFile[blk.File], blk)
	}

	for _, f := range order {
		fmt.Fprintf(&b, "## `%s`\n\n", f)
		for _, blk := range byFile[f] {
			if err := renderBlock(&b, blk, used); err != nil {
				return "", err
			}
		}
	}

	var unused []string
	for k := range nns.SchemaFieldDocs {
		if !used[k] {
			unused = append(unused, k)
		}
	}
	if len(unused) > 0 {
		sort.Strings(unused)
		return "", fmt.Errorf("SchemaFieldDocs has entries for fields that no longer exist: %s", strings.Join(unused, ", "))
	}
	renderHistory(&b)
	return b.String(), nil
}

const repoTree = "https://github.com/Swiss-Subnet/alpage/blob"

// placeholderRef matches a dotted reference carrying an angle-bracket
// placeholder (subnet.<name>.id, <kind>.<name>.id, replica_version_<id>).
var placeholderRef = regexp.MustCompile(`[A-Za-z_.]*<[a-z_]+>[A-Za-z_.<>]*`)

// cliFlag matches a long CLI flag at a word boundary, so "--force" becomes a
// code span while an em-dash-ish "well--formed" is left alone.
var cliFlag = regexp.MustCompile(`(^|[\s(])(--[a-z][a-z-]*)\b`)

// sinceTag renders a version as a chip the site styles; GitHub strips the span
// and shows the plain "v0.1.0", which reads fine either way.
func sinceTag(v string) string {
	return `<span class="since" title="Introduced in ` + v + `">` + v + `</span>`
}

// codePlaceholders wraps those references in backticks. Markdown renderers treat
// a bare <name> as an HTML tag and drop it, so the prose in nns/schema.go stays
// plain and the escaping happens here, at the one place that emits markdown.
func codePlaceholders(s string) string {
	s = placeholderRef.ReplaceAllStringFunc(s, func(m string) string {
		trimmed := strings.TrimRight(m, ".)")
		return "`" + trimmed + "`" + m[len(trimmed):]
	})
	return cliFlag.ReplaceAllString(s, "$1`$2`")
}

// headingSlug mirrors the site's heading-id scheme (and GitHub's): lowercase,
// punctuation dropped, whitespace to dashes. The block heading it targets ends
// in `{ }`, whose punctuation leaves the trailing dash.
func headingSlug(blockName string) string {
	// Drop punctuation first, then collapse whitespace runs, matching the
	// site's slugger: "add / remove" has to slug to add-remove, not add--remove.
	s := strings.ToLower(blockName + " { }")
	var cleaned strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_', r == '-', r == ' ':
			cleaned.WriteRune(r)
		}
	}
	return strings.TrimRight(strings.Join(strings.Fields(cleaned.String()), "-"), "-") + "-"
}

// linkBlockRefs turns a prose mention of another block ("See the add / remove
// block") into an in-page link. self names the block being rendered, so its own
// intro does not link to itself.
func linkBlockRefs(s string, self ...string) string {
	skip := ""
	if len(self) > 0 {
		skip = self[0]
	}
	// Longest name first: "add / remove" must win over a bare "add".
	names := make([]string, 0, len(nns.SchemaBlocks))
	for _, blk := range nns.SchemaBlocks {
		names = append(names, blk.Name)
	}
	sort.Slice(names, func(i, j int) bool { return len(names[i]) > len(names[j]) })

	for _, name := range names {
		if name == skip {
			continue
		}
		// Only a mention followed by "block", so ordinary prose using the word
		// (a node's "subnet" attribute) is left alone.
		re := regexp.MustCompile(`\b` + regexp.QuoteMeta(name) + `( block)`)
		s = re.ReplaceAllString(s, "["+name+"](#"+headingSlug(name)+")$1")
	}
	return s
}

// renderHistory lists every release named by a Since value, linking to that
// tag's copy of this file. Deriving the list from the schema keeps it from
// drifting; an unreleased version has no tag yet, so it is listed unlinked.
func renderHistory(b *strings.Builder) {
	seen := map[string]bool{}
	for _, v := range nns.SchemaFieldSince {
		seen[v] = true
	}
	for _, blk := range nns.SchemaBlocks {
		seen[blk.Since] = true
	}
	versions := make([]string, 0, len(seen))
	for v := range seen {
		versions = append(versions, v)
	}
	sort.Sort(sort.Reverse(sort.StringSlice(versions)))

	b.WriteString("## Schema History\n\n")
	b.WriteString("Each release's schema, as generated at that tag:\n\n")
	for _, v := range versions {
		if v == nns.SchemaUnreleased {
			fmt.Fprintf(b, "- **%s** (unreleased) - the schema above.\n", v)
			continue
		}
		fmt.Fprintf(b, "- [%s](%s/%s/docs/config.md)\n", v, repoTree, v)
	}
	b.WriteString("\n")
}

func renderBlock(b *strings.Builder, blk nns.SchemaBlock, used map[string]bool) error {
	header := blk.Name
	for _, l := range blk.Labels {
		header += fmt.Sprintf(" \"<%s>\"", l)
	}
	fmt.Fprintf(b, "### `%s { }`\n\n%s %s\n\n", header, sinceTag(blk.Since), linkBlockRefs(codePlaceholders(blk.Doc), blk.Name))

	fields, err := fieldsOf(blk, used)
	if err != nil {
		return err
	}
	if len(fields) == 0 {
		return nil
	}
	b.WriteString("| Field | Kind | Required | Since | Description |\n")
	b.WriteString("|-------|------|----------|-------|-------------|\n")
	for _, f := range fields {
		req := "yes"
		if f.Optional || f.Kind == "block" {
			req = "no"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s |\n", f.Name, f.Kind, req, sinceTag(f.Since), f.Doc)
	}
	b.WriteString("\n")
	return nil
}

func fieldsOf(blk nns.SchemaBlock, used map[string]bool) ([]field, error) {
	t := reflect.TypeOf(blk.Type)
	structName := t.Name()
	var out []field
	for _, sf := range hclFields(t) {
		tag := sf.Tag.Get("hcl")
		if tag == "" || tag == ",remain" {
			continue
		}
		name, opts, _ := strings.Cut(tag, ",")
		f := field{Name: name}
		switch {
		case strings.Contains(","+opts+",", ",label,") || opts == "label":
			f.Kind = "label"
		case strings.Contains(","+opts+",", ",block,") || opts == "block":
			f.Kind = "block"
		default:
			f.Kind = "attr"
		}
		f.Optional = strings.Contains(","+opts+",", ",optional,") || opts == "optional"

		if f.Kind == "label" {
			continue // labels are shown in the block header
		}
		key := structName + "." + name
		doc, ok := nns.SchemaFieldDocs[key]
		if !ok {
			return nil, fmt.Errorf("missing SchemaFieldDocs[%q] for %s block %q", key, blk.Name, name)
		}
		since, ok := nns.SchemaFieldSince[key]
		if !ok {
			return nil, fmt.Errorf("missing SchemaFieldSince[%q] for %s block %q", key, blk.Name, name)
		}
		used[key] = true
		f.Doc = linkBlockRefs(codePlaceholders(doc), blk.Name)
		f.Since = since
		out = append(out, f)
	}
	return out, nil
}

// hclFields returns the struct's fields in declaration order, recursing into
// embedded (anonymous) structs so a base like `named` flattens into the
// enclosing block, matching how gohcl decodes them.
func hclFields(t reflect.Type) []reflect.StructField {
	var out []reflect.StructField
	for i := 0; i < t.NumField(); i++ {
		sf := t.Field(i)
		if sf.Anonymous && sf.Type.Kind() == reflect.Struct {
			out = append(out, hclFields(sf.Type)...)
			continue
		}
		out = append(out, sf)
	}
	return out
}
